export const productActionTypes = {
  IS_LOADING: "IS_LOADING",
  FETCH_PRODUCTS: "FETCH_PRODUCTS",
  FETCH_CATEGORIES: "FETCH_CATEGORIES",
  GET_PRODUCT_DETAILS: "GET_PRODUCT_DETAILS",
};

export const filterTypes = {
  SEARCH_PRODUCT: "SEARCH_PRODUCT",
  FILTER_BY_PRICE: "FILTER_BY_PRICE",
  FILTER_BY_CATEGORY: "FILTER_BY_CATEGORY",
  FILTER_BY_RATING: "FILTER_BY_RATING",
  SORT: "SORT",
  CLEAR_FILTER: "CLEAR_FILTER",
};
