export const productActionTypes = {
  IS_LOADING: "IS_LOADING",
  FETCH_PRODUCTS: "FETCH_PRODUCTS",
  FETCH_CATEGORIES: "FETCH_CATEGORIES",
  GET_PRODUCT_DETAILS: "GET_PRODUCT_DETAILS",
};

export const filterActionTypes = {
  SEARCH_PRODUCT: "SEARCH_PRODUCT",
  FILTER_BY_PRICE: "FILTER_BY_PRICE",
  FILTER_BY_CATEGORY: "FILTER_BY_CATEGORY",
  FILTER_BY_RATING: "FILTER_BY_RATING",
  SORT: "SORT",
  CLEAR_FILTER: "CLEAR_FILTER",
  FILTER_BY_STOCK: "FILTER_BY_STOCK",
};

export const cartActionTypes = {
  IS_LOADING_CART: "IS_LOADING_CART",
  GET_CART: "GET_CART",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  UPDATE_CART: "UPDATE_CART",
};

export const wishListActionTypes = {
  IS_LOADING_WIHSLIST: "IS_LOADING_WISHLIST",
  GET_WISHLIST: "GET_WISHLIST",
  ADD_TO_WISHLIST: "ADD_TO_WISHLIST",
  REMOVE_FROM_WISHLIST: "REMOVE_FROM_WISHLIST",
};
